"use client";

import type { DirectMaterialBatchView, DirectMaterialInformation, DirectMaterialProcessingStage, MainMaterialCategoryCode } from "@shanyu/contracts";
import { Check, ChevronLeft, ChevronRight, Download, FileSpreadsheet, ImageIcon, Upload } from "lucide-react";
import Image from "next/image";
import { useRef, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect } from "@/components/ui/native-select";
import { createDirectUploadRequestId, DirectImportError, downloadDirectBlob, downloadDirectReference, previewDirectMaterials, publishDirectMaterials, uploadDirectMaterials } from "@/lib/main-material-direct-client";
import { directChangeCounts, directUnitOptions, directUnitValue } from "@/lib/main-material-direct-result";

const categories: [MainMaterialCategoryCode, string][] = [["TILE","瓷砖"],["SEAM","美缝"],["FLOOR","木地板"],["GLASS_DOOR","玻璃门"],["CEILING","集成吊顶"],["BATHROOM","卫浴"],["SHOWER","淋浴房"],["STONE","石材/岩板"],["SWITCH","开关面板"],["CUSTOM","定制类"]];
const results = { NEW: "新增", UPDATE: "更新", SKIP: "跳过", EXCLUDE: "排除", UNRESOLVED: "待处理" };
const fieldLabels:Record<string,string>={itemName:"品名",brand:"品牌",series:"系列",process:"工艺",model:"型号",spec:"规格",colors:"颜色",unit:"单位",costPrice:"成本",salePrice:"售价",remarks:"备注",status:"资料状态"};
type RowInfo = NonNullable<DirectMaterialInformation["rows"]>[string];
function Photo({ url, large = false }: { url?: string; large?: boolean }) {
  return <div className={`relative flex items-center justify-center overflow-hidden rounded-md bg-muted ${large ? "h-48 w-full" : "h-14 w-14 shrink-0"}`}>{url ? <Image src={url} alt="来源产品图" fill unoptimized className="object-contain" /> : <ImageIcon className="text-muted-foreground" />}</div>;
}
function SelectField({ label, value, options, onChange }: { label: string; value?: string; options: readonly (readonly [string,string])[]; onChange: (value: string) => void }) {
  return <label className="grid gap-2 text-sm"><span>{label}</span><NativeSelect aria-label={label} value={value ?? ""} onChange={event => onChange(event.target.value)}><option value="">请选择</option>{options.map(([key, text]) => <option value={key} key={key}>{text}</option>)}</NativeSelect></label>;
}

export function MainMaterialImportForm({ currentItemCount, currentVersionNumber }: { readonly currentItemCount: number; readonly currentVersionNumber: number | null }) {
  const [file, setFile] = useState<File | null>(null), [images, setImages] = useState<File[]>([]);
  const [batch, setBatch] = useState<DirectMaterialBatchView | null>(null), [information, setInformation] = useState<DirectMaterialInformation>({});
  const [working, setWorking] = useState(false), [error, setError] = useState(""), [unsupported, setUnsupported] = useState(false);
  const [infoOpen, setInfoOpen] = useState(false), [confirmOpen, setConfirmOpen] = useState(false), [reason, setReason] = useState("");
  const [rowOpen, setRowOpen] = useState<number | null>(null), [imageOpen, setImageOpen] = useState<string | null>(null);
  const [filter, setFilter] = useState("ALL"), [search, setSearch] = useState(""), [page, setPage] = useState(0), [gallery, setGallery] = useState(false);
  const [processing, setProcessing] = useState<DirectMaterialProcessingStage | "UPLOADING" | "PUBLISHING" | null>(null);
  const [detailsOpen, setDetailsOpen] = useState(false), [detailsPage, setDetailsPage] = useState(0);
  const operation = useRef<{ file: File; images: readonly File[]; id: string } | null>(null);
  const abort = useRef<AbortController | null>(null);
  function accept(result: DirectMaterialBatchView) { setBatch(result); setInformation(result.information); setReason(""); setConfirmOpen(false); setPage(0); }
  function failure(caught: unknown) { setError(caught instanceof Error ? caught.message : "操作失败，请重试"); setUnsupported(caught instanceof DirectImportError && caught.kind === "UNSUPPORTED"); }
  async function upload(chosen = file) {
    if (!chosen) return; setWorking(true); setProcessing("UPLOADING"); setError(""); setUnsupported(false); const controller = new AbortController(); abort.current = controller;
    if (operation.current?.file !== chosen || operation.current.images !== images) operation.current = { file: chosen, images, id: createDirectUploadRequestId() };
    try { const result = await uploadDirectMaterials(chosen, images, controller.signal, operation.current.id, setProcessing); accept(result); setInfoOpen(result.needsInformation); }
    catch (caught) { if (!controller.signal.aborted) failure(caught); }
    finally { setWorking(false); setProcessing(null); abort.current = null; }
  }
  async function validate(next = information, close = false) {
    if (!batch) return; setWorking(true); setProcessing("VALIDATING"); setError("");
    try { const result = await previewDirectMaterials(batch, next); accept(result); if (close) setInfoOpen(false); return true; }
    catch (caught) { failure(caught); return false; } finally { setWorking(false); setProcessing(null); }
  }
  function rowInfo(row: number, patch: RowInfo) { return { ...information, rows: { ...information.rows, [row]: { ...information.rows?.[row], ...patch } } }; }
  async function decide(row: number, decision: "SKIP" | "EXCLUDE") { if(await validate(rowInfo(row, { decision }))) setRowOpen(null); }
  async function decideGroup(keep: number | null) {
    if (!selected) return;
    const next={...information,rows:{...information.rows}};
    for (const row of selected.duplicateRows) next.rows[row]={...next.rows[row],decision:row===keep ? undefined : "EXCLUDE"};
    if(await validate(next)) setRowOpen(null);
  }
  function updateRow(row: number, patch: RowInfo) { setInformation(rowInfo(row, patch)); }
  async function publish() {
    if (!batch) return; setWorking(true); setProcessing("PUBLISHING"); setError("");
    try { accept(await publishDirectMaterials(batch, reason.trim())); setConfirmOpen(false); }
    catch (caught) { failure(caught); setConfirmOpen(false); } finally { setWorking(false); setProcessing(null); }
  }
  const rows = batch?.rows ?? [], selected = rows.find(row => row.row === rowOpen);
  const changes = directChangeCounts(rows);
  const stageText = processing ? { UPLOADING:"上传中…", READING:"文件读取中…", IMAGES:"图片处理中…", VALIDATING:"校验中…", PUBLISHING:"发布中…" }[processing] : "";
  const filtered = rows.filter(row => (filter === "ALL" || row.result === filter || (filter === "WARNING" && row.warnings.length > 0)) && JSON.stringify([row.row,row.values,row.itemName]).toLowerCase().includes(search.toLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length / 5)), actualPage = Math.min(page, pages - 1);
  const groups = Array.from(new Map(rows.filter(row=>row.issues.some(issue=>issue.includes("品名须确认"))).map(row => [[row.values.brand,row.values.series,row.values.process].join(" / "), row] as const)).entries());
  const step = batch?.published || confirmOpen ? 4 : batch ? batch.needsInformation || batch.counts.unresolved ? 2 : 3 : working ? 1 : 0;
  const modalGuard = { onEscapeKeyDown: (event: Event) => { if (working) event.preventDefault(); }, onPointerDownOutside: (event: Event) => { if (working) event.preventDefault(); } };
  function problems() {
    const quote = (value: string) => `"${(/^[=+@-]/.test(value) ? "'" : "") + value.replaceAll('"','""')}"`;
    const text = ["来源行,品牌,型号,结果,处理依据,字段变化,原图哈希,可见图哈希,问题,警告", ...rows.map(row => [String(row.row),row.values.brand ?? "",row.values.model ?? "",results[row.result],row.reason,row.differences.map(d=>`${fieldLabels[d.field] ?? d.field}：${d.before} → ${d.after}`).join("；"),row.images.map(i=>i.originalHash).join("；"),row.images.map(i=>i.visibleHash).join("；"),row.issues.join("；"),row.warnings.join("；")].map(quote).join(","))].join("\r\n");
    downloadDirectBlob(new Blob(["\uFEFF",text], { type: "text/csv;charset=utf-8" }), "主材导入问题清单.csv");
  }
  return <div className="grid min-w-0 gap-4">
    {processing && <p role="status" aria-live="polite" className="rounded-md bg-primary-soft p-3 text-sm text-primary">{stageText} {processing === "PUBLISHING" ? "完成后将显示实际发布结果。" : "尚未发布，完成校验后请复核并确认。"}</p>}
    <nav aria-label="导入进度" className="grid grid-cols-5 gap-2 rounded-lg border border-border bg-background p-4">{["选择文件","自动识别与校验","资料与异常处理","差异预览","确认发布"].map((text,index) => <div key={text} className={`flex items-center gap-2 text-xs ${index <= step ? "text-primary" : "text-muted-foreground"}`}><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${index <= step ? "bg-primary text-white" : "bg-muted"}`}>{index < step ? <Check size={14} /> : index + 1}</span>{text}</div>)}</nav>
    {error && <div role="alert" className="grid gap-2 rounded-lg border border-border border-destructive/20 bg-destructive/5 p-4 text-sm text-destructive"><strong>本次未发布</strong><span>{error}</span>{unsupported && <div><p>请将资料整理为参考文件的 Sheet2 结构；Sheet1 为历史资料，不会合并。原文件无需改写，可另存为副本。</p><Button variant="outline" onClick={() => downloadDirectReference().catch(failure)}><Download />下载参考模板</Button></div>}</div>}
    {!batch ? <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]">
      <Card className="border-border shadow-none"><CardContent className="grid gap-4 p-5"><div><h2 className="type-section-title">选择 Excel 文件</h2><p className="mt-2 text-sm text-muted-foreground">支持 .xlsx，保留原表内容及嵌入图片。</p></div>
        <label className="grid cursor-pointer justify-items-center gap-3 rounded-lg bg-muted p-10 text-center" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); if(!working) {const chosen=event.dataTransfer.files[0] ?? null;setFile(chosen);void upload(chosen);} }}><FileSpreadsheet className="h-10 w-10 text-primary" /><strong>{file?.name ?? "将文件拖入此处，或点击选择文件"}</strong><span className="text-sm text-muted-foreground">正常文件无需整理为固定列数，也无需手工复制图片。</span><Input aria-label="客户 Excel 文件" accept=".xlsx" type="file" className="max-w-sm" disabled={working} onChange={event => { const chosen=event.target.files?.[0] ?? null;setFile(chosen);void upload(chosen); }} /></label>
        <details className="text-sm text-muted-foreground"><summary>使用文件名关联的配套图片（可选）</summary><Input aria-label="配套图片" type="file" accept="image/*" multiple onChange={event => setImages(Array.from(event.target.files ?? []))} /></details>
        <div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">当前 V{currentVersionNumber ?? 0} · {currentItemCount} 条主材</span><div className="flex gap-2">{working && <Button variant="outline" onClick={() => abort.current?.abort()}>取消上传</Button>}<Button disabled={!file || working} onClick={()=>upload()}><Upload />{working ? "识别与校验中…" : "上传并校验"}</Button></div></div></CardContent></Card>
      <Card className="h-fit border-border shadow-none"><CardContent className="grid gap-4 p-5"><h2 className="type-section-title">接下来会发生什么</h2><p className="text-sm text-muted-foreground">自动识别工作表与字段，仅对不明确资料集中确认。</p><p className="text-sm text-muted-foreground">完全重复跳过；同一商品有变化自动列为更新。</p><p className="text-sm text-muted-foreground">查看差异并确认后发布，不自动修改已有项目和历史报价。</p></CardContent></Card>
    </div> : batch.published ? <>
      <div className="rounded-lg bg-green-50 p-4 text-sm text-green-800"><h2 className="font-semibold">主材库发布成功</h2><p className="mt-1">本次确认的商品及图片已发布，新主材库版本已生效。</p></div>
      <div className="grid grid-cols-5 gap-3">{[["实际新增",batch.counts.added],["实际更新",batch.counts.updated],["实际跳过",batch.counts.skipped],["实际排除",batch.counts.excluded],["待补／警告",`${batch.counts.pending} / ${batch.counts.warnings}`]].map(([label,value])=><Card key={label} className="border-border shadow-none"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><strong className="text-2xl">{value}</strong></CardContent></Card>)}</div>
      <Card className="border-border shadow-none"><CardContent className="grid gap-4 p-5"><dl className="grid gap-3 text-sm"><div className="flex justify-between border-b border-border pb-3"><dt>已发布版本</dt><dd>V{batch.published.versionNumber}</dd></div><div className="flex justify-between border-b border-border pb-3"><dt>发布前商品总数 → 发布后商品总数</dt><dd>{batch.currentCount} → {batch.published.itemCount}</dd></div><div className="flex justify-between gap-3"><dt>价格变化／图片变化</dt><dd>{changes.prices} / {changes.images}</dd></div></dl><div className="flex gap-2"><Button variant="outline" onClick={()=>{setDetailsPage(0);setDetailsOpen(true);}}>查看本次发布明细</Button><Button variant="outline" onClick={()=>{setBatch(null);setFile(null);operation.current=null;}}>继续导入</Button></div></CardContent></Card>
      <Card className="border-border shadow-none"><CardContent className="p-5"><h3 className="font-semibold">哪些项目会使用新版本</h3><p className="mt-2 text-sm text-muted-foreground">新建项目可使用本次已发布版本。已有项目保持原绑定版本，需主动检查更新；历史报价不变。未涉及的商品、颜色、选项及其图片保持原样。</p></CardContent></Card>
    </> : selected ? null : <>
      <Card className="border-border shadow-none"><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{batch.fileName}</strong><p className="mt-1 text-sm text-muted-foreground">{batch.selectedSheet ?? "待选择工作表"} · 读取 {batch.counts.read} 条 · {rows.reduce((n,row) => n + row.images.length,0)} 张图片 · V{batch.baseVersion} → {batch.canPublish ? `V${batch.baseVersion+1}` : "待确认"}</p></div><div className="flex gap-2"><Button variant="outline" disabled={working} onClick={() => { setInformation(batch.information); setInfoOpen(true); }}>补充／确认资料</Button><Button variant="outline" disabled={working} onClick={() => validate()}>重新校验</Button><Button variant="outline" disabled={working} onClick={() => { setBatch(null); setFile(null); }}>更换文件</Button></div></CardContent></Card>
      <div className="grid grid-cols-3 gap-3 xl:grid-cols-6">{([["新增",batch.counts.added],["更新",batch.counts.updated],["跳过",batch.counts.skipped],["排除",batch.counts.excluded],["未解决",batch.counts.unresolved],["待补／警告",`${batch.counts.pending} / ${batch.counts.warnings}`]] as const).map(([label,value]) => <Card key={label} className="border-border shadow-none"><CardContent className="p-4"><p className="text-sm text-muted-foreground">{label}</p><strong className="text-2xl">{value}</strong></CardContent></Card>)}</div>
      <Card className="min-w-0 overflow-hidden py-0 border-border shadow-none"><CardContent className="p-0"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border p-4"><h2 className="type-section-title">导入预览与差异</h2><div className="flex flex-wrap gap-2"><Input aria-label="搜索主材" placeholder="搜索品牌、型号或来源行" className="w-48" value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} /><NativeSelect aria-label="结果筛选" value={filter} onChange={event => { setFilter(event.target.value); setPage(0); }}><option value="ALL">全部结果</option>{Object.entries(results).map(([key,value]) => <option key={key} value={key}>{value}</option>)}<option value="WARNING">警告</option></NativeSelect><Button variant="outline" onClick={() => setGallery(!gallery)}>{gallery ? "列表" : "图片核对"}</Button><Button variant="outline" onClick={problems}><Download />问题清单</Button></div></div>
        {gallery ? <div className="grid grid-cols-3 gap-4 p-4 xl:grid-cols-5">{filtered.map(row => <button key={row.row} onClick={() => setImageOpen(row.images[0]?.url ?? null)} className="grid gap-2 rounded-md border border-border p-3 text-left"><Photo url={row.images[0]?.url} large /><span className="text-sm">第{row.row}行 · {row.values.brand} {row.values.model}</span><span className="text-xs text-muted-foreground">{row.values.spec} · {results[row.result]}</span></button>)}</div> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] table-fixed text-sm"><thead className="bg-muted text-left text-muted-foreground"><tr><th className="w-24 p-3">图片／来源</th><th className="p-3">品牌／型号／工艺／系列</th><th className="w-28 p-3">规格／单位</th><th className="w-28 p-3">成本／售价</th><th className="w-24 p-3">结果</th><th className="sticky right-0 w-28 bg-muted p-3">操作</th></tr></thead><tbody>{filtered.slice(actualPage*5,actualPage*5+5).map(row => <tr key={row.row} className="border-t border-border align-top"><td className="p-3"><button onClick={() => setImageOpen(row.images[0]?.url ?? null)}><Photo url={row.images[0]?.url} /></button><p className="mt-1 text-xs text-muted-foreground">第 {row.row} 行</p></td><td className="break-words p-3"><strong>{row.values.brand} · {row.values.model}</strong><p className="mt-1">{row.itemName || "品名待确认"}</p><p className="text-xs text-muted-foreground">{row.values.series} · {row.values.process}</p></td><td className="break-words p-3">{row.values.spec || "—"}<p className="mt-1 text-muted-foreground">{row.values.unit || information.rows?.[row.row]?.unit || information.unit || "单位待确认"}</p></td><td className="p-3">成本 {row.values.costPrice || (information.ambiguousPriceMeaning === "costPrice" ? row.values.ambiguousPrice : "") || "—"}<p className="mt-1">售价 {row.values.salePrice || "—"}</p></td><td className="p-3"><Badge variant={row.result === "UNRESOLVED" ? "destructive" : "secondary"}>{results[row.result]}</Badge>{row.pending && <p className="mt-1 text-xs text-amber-600">待补资料</p>}</td><td className="sticky right-0 bg-background p-3"><Button size="sm" variant="outline" disabled={working} onClick={() => { setInformation(batch.information); setRowOpen(row.row); }}>{row.result === "UNRESOLVED" ? "处理异常" : "查看详情"}</Button></td></tr>)}</tbody></table>{!filtered.length && <p className="p-10 text-center text-sm text-muted-foreground">没有符合条件的记录</p>}</div>}
        {!gallery && <div className="flex items-center justify-between border-t border-border p-3 text-sm text-muted-foreground"><span>共 {filtered.length} 条 · 第 {actualPage+1}/{pages} 页</span><div className="flex gap-1"><Button aria-label="上一页" size="sm" variant="outline" disabled={actualPage===0} onClick={() => setPage(actualPage-1)}><ChevronLeft /></Button><Button aria-label="下一页" size="sm" variant="outline" disabled={actualPage===pages-1} onClick={() => setPage(actualPage+1)}><ChevronRight /></Button></div></div>}</CardContent></Card>
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-background p-4"><p className="text-sm text-muted-foreground">{batch.canPublish ? `实际变化 ${batch.counts.added + batch.counts.updated} 条；请查看差异后确认发布。` : batch.counts.unresolved || batch.needsInformation ? "请先完成资料确认和未解决项。" : "本次无实际变化，不生成新版本。"}</p><Button disabled={working || !batch.canPublish} onClick={() => { setError(""); setReason(""); setConfirmOpen(true); }}>查看摘要并确认发布</Button></div>
    </>}
    <Dialog open={infoOpen} onOpenChange={open => { if (!working) setInfoOpen(open); }}><DialogContent className="border-border max-h-[90vh] overflow-y-auto sm:max-w-[980px]" {...modalGuard}><DialogHeader><DialogTitle>补充并确认必要资料</DialogTitle><DialogDescription>仅确认无法从原文件明确识别的资料。价格按本行单位，不自动换算；品名仅可从已有值选择。</DialogDescription></DialogHeader>{batch && <>
      {batch.sheets.length > 1 && <div className="grid gap-2">{batch.sheets.map(sheet => <label key={sheet.name} className="flex gap-3 rounded-lg border border-border p-3 text-sm"><input type="radio" name="source-sheet" value={sheet.name} disabled={working} checked={information.sheet===sheet.name} onChange={() => { const next={...information,sheet:sheet.name};setInformation(next);void validate(next); }} /><span><strong>{sheet.name}</strong> · {sheet.rowCount} 条 · {sheet.imageCount} 张图片<p className="text-xs text-muted-foreground">{sheet.sample.map(item => `${item.brand ?? ""} ${item.model ?? item.itemName ?? ""}`).join("、")}</p></span></label>)}</div>}
      <p className="rounded-md bg-muted p-3 text-sm">读取 {information.sheet ?? batch.selectedSheet ?? "待选择"}；忽略 {[...batch.ignoredSheets,...batch.sheets.filter(sheet => sheet.name !== (information.sheet ?? batch.selectedSheet)).map(sheet => sheet.name)].join("、") || "无"}，不会合并历史资料。</p>
      <div className="grid gap-3 sm:grid-cols-3">{(rows.some(row=>!row.categoryCode)||information.categoryCode) && <SelectField label="分类" value={information.categoryCode} options={categories} onChange={value => { const next = { ...information, categoryCode: value as MainMaterialCategoryCode, rows: Object.fromEntries(Object.entries(information.rows ?? {}).map(([row,choice])=>[row,{...choice,itemName:undefined}])) }; setInformation(next); void validate(next); }} />}{(rows.some(row=>!row.values.unit)||information.unit) && <SelectField label="计价单位" value={directUnitValue(information.unit)} options={directUnitOptions} onChange={value => setInformation({ ...information, unit: value })} />}{batch.ambiguousPriceLabel && <SelectField label={`“${batch.ambiguousPriceLabel}”的含义`} value={information.ambiguousPriceMeaning} options={[["costPrice","成本单价"],["salePrice","售价单价"]]} onChange={value => setInformation({ ...information, ambiguousPriceMeaning: value as "costPrice" | "salePrice" })} />}</div>
      <div className="grid gap-3"><h3 className="font-semibold">按一致来源分组确认品名</h3>{groups.map(([group,row]) => { const members = rows.filter(item => [item.values.brand,item.values.series,item.values.process].join(" / ")===group), value = information.rows?.[row.row]?.itemName ?? ""; return <div key={group} className="grid items-start gap-3 rounded-md border border-border p-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_200px]"><div className="text-sm"><strong>{group} · {members.length} 条</strong><p className="mt-1 text-xs text-muted-foreground">{members.map(item => item.values.model).join("、")}</p></div><div>{row.suggestedName ? <p className="mt-2 text-primary">建议：{row.suggestedName}（待确认） · {row.suggestionReason}</p> : <p className="text-xs text-muted-foreground">{row.suggestionReason}</p>}</div><SelectField label={`${row.values.brand || group}分组品名`} value={value} options={(batch.nameOptions[information.categoryCode ?? row.categoryCode ?? "TILE"] ?? []).map(name => [name,name])} onChange={name => { const next = { ...information.rows }; members.forEach(item => { next[item.row] = { ...next[item.row], itemName: name }; }); setInformation({ ...information, rows: next }); }} /></div>; })}</div>
      <details className="text-sm"><summary>逐行确认（不同分类或品名时）</summary><div className="mt-3 grid gap-3">{rows.map(row => <div key={row.row} className="grid gap-3 rounded-md border border-border p-3 sm:grid-cols-[1fr_160px_200px_140px]"><span>第{row.row}行 · {row.values.model}</span><SelectField label={`第${row.row}行分类`} value={information.rows?.[row.row]?.categoryCode ?? information.categoryCode ?? row.categoryCode ?? ""} options={categories} onChange={value => updateRow(row.row,{ categoryCode: value as MainMaterialCategoryCode, itemName: "" })} /><SelectField label={`第${row.row}行品名`} value={information.rows?.[row.row]?.itemName ?? ""} options={(batch.nameOptions[information.rows?.[row.row]?.categoryCode ?? information.categoryCode ?? row.categoryCode ?? "TILE"] ?? []).map(name => [name,name])} onChange={value => updateRow(row.row,{ itemName: value })} /><SelectField label={`第${row.row}行单位`} value={directUnitValue(information.rows?.[row.row]?.unit ?? row.values.unit ?? information.unit)} options={directUnitOptions} onChange={value=>updateRow(row.row,{unit:value})}/></div>)}</div></details>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={working} onClick={() => setInfoOpen(false)}>取消</Button><Button disabled={working} onClick={() => validate(information,true)}>{working ? "校验中…" : "确认资料并校验"}</Button></div>
    </>}</DialogContent></Dialog>
    <Dialog open={detailsOpen} onOpenChange={setDetailsOpen}><DialogContent className="border-border max-h-[90vh] overflow-y-auto sm:max-w-[980px]"><DialogHeader><DialogTitle>本次发布明细</DialogTitle><DialogDescription>V{batch?.published?.versionNumber} · 共 {rows.length} 款资料。仅新增和更新商品在本次发布中生效。</DialogDescription></DialogHeader>
      <div className="grid gap-3">{rows.slice(detailsPage*5,detailsPage*5+5).map(row => {
        const value = (field: string) => row.differences.find(diff => diff.field === field)?.after || row.values[field] || (field === "costPrice" && batch?.information.ambiguousPriceMeaning === "costPrice" ? row.values.ambiguousPrice : "") || (field === "unit" ? batch?.information.rows?.[row.row]?.unit || batch?.information.unit : "") || "—";
        return <article key={row.row} className="grid gap-3 rounded-md border border-border p-3 sm:grid-cols-[56px_minmax(0,1fr)]"><Photo url={row.images[0]?.url || row.oldImageUrls[0]} /><div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="break-words">{row.itemName || value("itemName")} · {value("model")}</strong><Badge variant="secondary">{results[row.result]}</Badge></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-3">{[["分类",categories.find(([code]) => code === row.categoryCode)?.[1] || "—"],["品牌",value("brand")],["规格",value("spec")],["单位",value("unit")],["成本",value("costPrice")],["售价",value("salePrice")]].map(([label,content]) => <div key={label} className="min-w-0"><dt className="text-muted-foreground">{label}</dt><dd className="break-words">{content}</dd></div>)}</dl>{row.result === "UPDATE" && <details className="mt-3 text-sm"><summary>查看前后差异</summary><dl className="mt-2 grid gap-2">{row.differences.map(diff => <div key={diff.field} className="grid gap-1 border-t border-border pt-2 sm:grid-cols-[100px_minmax(0,1fr)]"><dt>{fieldLabels[diff.field] || diff.field}</dt><dd className="break-words">{diff.field === "产品图" ? "产品图已更新" : `${diff.before} → ${diff.after}`}</dd></div>)}</dl></details>}{["SKIP","EXCLUDE"].includes(row.result) && <p className="mt-2 text-sm text-muted-foreground">{row.reason}</p>}</div></article>;
      })}</div><div className="flex items-center justify-between gap-2 text-sm"><span>第 {detailsPage+1}/{Math.max(1,Math.ceil(rows.length/5))} 页</span><div className="flex gap-2"><Button variant="outline" disabled={detailsPage===0} onClick={()=>setDetailsPage(detailsPage-1)}>上一页</Button><Button variant="outline" disabled={(detailsPage+1)*5>=rows.length} onClick={()=>setDetailsPage(detailsPage+1)}>下一页</Button><Button variant="outline" onClick={()=>setDetailsOpen(false)}>关闭</Button></div></div>
    </DialogContent></Dialog>
    {selected && <section role="region" aria-label="商品差异与异常处理" className="grid gap-4"><div className={`rounded-md p-3 text-sm ${selected.issues.length ? "bg-destructive/5 text-destructive" : "bg-primary-soft text-primary"}`}><h2 className="font-semibold">第 {selected.row} 行 · {selected.values.model} · {results[selected.result]}</h2><p className="mt-1">{selected.reason}</p></div><div className="grid items-stretch gap-4 lg:grid-cols-2"><Card className="border-border shadow-none"><CardContent className="grid gap-4 p-4">
      <div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-sm">当前图片</p><Photo url={selected.oldImageUrls[0]} large /></div><div><p className="mb-2 text-sm">本次可见图片</p><Photo url={selected.images[0]?.url} large /></div></div>
      <dl className="grid gap-2 text-sm">{["brand","model","spec","unit"].map(field=><div key={field} className="flex justify-between gap-3 border-b border-border pb-2"><dt>{fieldLabels[field]}</dt><dd className="break-words">{selected.values[field] || "—"}</dd></div>)}</dl>
      {selected.differences.length > 0 && <table className="w-full table-fixed text-sm"><thead className="bg-muted"><tr><th className="p-2 text-left">字段</th><th className="p-2 text-left">当前值</th><th className="p-2 text-left">本次值</th></tr></thead><tbody>{selected.differences.map(diff => <tr key={diff.field} className="border-t border-border"><td className="break-words p-2">{fieldLabels[diff.field] ?? diff.field}</td><td className="break-words p-2">{diff.before || "—"}</td><td className="break-words p-2">{diff.after || "—"}</td></tr>)}</tbody></table>}
      </CardContent></Card><Card className="border-border shadow-none"><CardContent className="grid content-start gap-4 p-4"><h3 className="font-semibold">{selected.duplicateRows.length>1 ? "重复组 · 同一商品出现不同内容" : "匹配依据与处理"}</h3><p className="text-sm text-muted-foreground">{selected.reason}</p>
      {selected.issues.length > 0 && <ul className="rounded-md bg-destructive/5 p-3 text-sm text-destructive">{selected.issues.map(issue => <li key={issue}>{issue}</li>)}</ul>}
      {selected.candidates.map(candidate => <div key={candidate.materialId} className="rounded-md border border-border p-3 text-sm"><strong>已有候选：{candidate.model}</strong><p className="mt-1 break-all text-muted-foreground">{candidate.status} · {candidate.materialId}</p></div>)}
      {selected.duplicateRows.length>1 && <div className="grid gap-2">{rows.filter(row=>selected.duplicateRows.includes(row.row)).map(row=><label key={row.row} className="flex gap-2 rounded-md border border-border p-3 text-sm"><input type="radio" name="duplicate-row" checked={row.row===selected.row} disabled={working} onChange={()=>setRowOpen(row.row)} /><span>第 {row.row} 行 · {row.values.model}<p className="mt-1 text-muted-foreground">成本 {row.values.costPrice || "—"} · 售价 {row.values.salePrice || "—"}</p></span></label>)}</div>}
      <details><summary className="text-sm">补充／更正本行资料</summary><div className="mt-3 grid gap-3 sm:grid-cols-3">{["brand","model","spec","costPrice","salePrice","remarks"].map(field => <label key={field} className="grid gap-2 text-sm">{{ brand:"品牌",model:"型号",spec:"规格",costPrice:"成本",salePrice:"售价",remarks:"备注" }[field]}<Input value={information.rows?.[selected.row]?.values?.[field] ?? selected.values[field] ?? ""} onChange={event => updateRow(selected.row,{ values: { ...information.rows?.[selected.row]?.values, [field]: event.target.value } })} /></label>)}</div></details>
      <p className="text-sm text-muted-foreground">处理决定改变后重新校验全部差异。更新候选无需逐行确认，最终发布前统一复核。</p></CardContent></Card></div>
      <div className="flex flex-wrap justify-end gap-2">{selected.candidates.length>0 && <Button variant="outline" disabled={working} onClick={() => decide(selected.row,"SKIP")}>保留原商品并跳过</Button>}{selected.duplicateRows.length>1 && <><Button variant="outline" disabled={working} onClick={()=>decideGroup(selected.row)}>仅保留此行</Button><Button variant="outline" disabled={working} onClick={()=>decideGroup(null)}>排除整组</Button></>}<Button variant="outline" disabled={working} onClick={() => decide(selected.row,"EXCLUDE")}>排除此行</Button><Button disabled={working} onClick={async () => { if(await validate()) setRowOpen(null); }}>保存处理并重新校验</Button></div>
      <div className="flex justify-end border-t border-border pt-3"><Button variant="outline" disabled={working} onClick={()=>setRowOpen(null)}>返回差异预览</Button></div></section>}
    <Dialog open={confirmOpen} onOpenChange={open => { if (!working) setConfirmOpen(open); }}><DialogContent className="border-border max-h-[90vh] overflow-y-auto sm:max-w-[800px]" {...modalGuard}><DialogHeader><DialogTitle>确认发布主材库</DialogTitle><DialogDescription>请复核本次商品、价格及图片变化后确认发布，发布原因可选填。</DialogDescription></DialogHeader>{batch && <><div className="rounded-md bg-primary-soft p-4"><strong>V{batch.baseVersion} → V{batch.baseVersion+1}</strong><p className="mt-2 text-sm">主材总数 {batch.currentCount} → {batch.expectedCount}</p></div><div className="grid grid-cols-3 gap-3 text-sm"><p>读取 {batch.counts.read}</p><p>新增 {batch.counts.added}</p><p>更新 {batch.counts.updated}</p><p>跳过 {batch.counts.skipped}</p><p>排除 {batch.counts.excluded}</p><p>未解决 {batch.counts.unresolved}</p><p>待补资料 {batch.counts.pending}</p><p>警告 {batch.counts.warnings}</p><p>图片变更 {rows.filter(row => row.differences.some(diff => diff.field === "产品图") || row.result === "NEW" && row.images.length).length}</p></div><div className="rounded-md bg-muted p-3 text-sm">只发布以上新增与更新；保留未涉及商品、色卡、选项及分组关系。不更新已有项目，不重算历史报价。</div><Label htmlFor="direct-publish-reason">发布原因（选填）</Label><Input id="direct-publish-reason" value={reason} disabled={working} placeholder="说明本次新增或更正内容" onChange={event => setReason(event.target.value)} /><div className="flex justify-end gap-2"><Button variant="outline" disabled={working} onClick={() => setConfirmOpen(false)}>取消</Button><Button disabled={working || !batch.canPublish} onClick={publish}>{working ? "发布中…" : "确认发布"}</Button></div></>}</DialogContent></Dialog>
    <Dialog open={!!imageOpen} onOpenChange={open => { if (!open) setImageOpen(null); }}><DialogContent className="border-border sm:max-w-[720px]"><DialogHeader><DialogTitle>本次商品可见图片</DialogTitle><DialogDescription>已按原 Excel 的裁剪、拉伸、翻转和旋转还原。</DialogDescription></DialogHeader><Photo url={imageOpen ?? undefined} large /></DialogContent></Dialog>
  </div>;
}
